
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2
profile: 'developer'
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  jaffle_shop:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  # public bigquery dataset available, other platforms require source data load from S3
  source_db: "{{ 'dbt-tutorial' if target.type == 'bigquery' else target.database }}"
